### PR TITLE
feat: bump deps for v0.7.0 release

### PR DESCRIPTION
**Pull request by MichaelMure**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Even with the bump, `Error: error loading plugins: loading plugin /home/circleci/.ipfs/plugins/go-ds-s3.so: plugin.Open("/home/circleci/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package internal/cpu` is still there.

Should it be built with a specific go version?

**Comment by aschmahmann** [comment]
@MichaelMure there were some changes to how we build releases that affect plugins. From the release notes highlights:

>🔌 Plugin build changes 🚨
We have changed the build flags used by the official binary distributions on dist.ipfs.io (or /ipns/dist.ipfs.io) to use the simpler and more reliable -trimpath flag instead of the more complicated and brittle -asmflags=all=-trimpath="$(GOPATH)" -gcflags=all=-trimpath="$(GOPATH)" flags, however the build flags used by default in go-ipfs remain the same.
>
>The scripts in https://github.com/ipfs/go-ipfs-example-plugin have been updated to reflect this change. This is a breaking change to how people have been building plugins against the dist.ipfs.io binary of go-ipfs and plugins should update their build processes accordingly see ipfs/go-ipfs-example-plugin#9 for details.

Do you have any recommendations on how to better announce this (or future) changes that result in breakages to the plugin build process?

**Comment by ianopolous** [comment]
I can confirm it loads correctly when built with -trimpath.

**Comment by MichaelMure** [comment]
> Do you have any recommendations on how to better announce this (or future) changes that result in breakages to the plugin build process?

It's the correct way IMHO, I just need to open my eyes (no promises).

I updated the makefile and the localstack port (see https://github.com/localstack/localstack/releases/tag/v0.11.5, who doesn't like a breaking change in a patch version).

**Review by aschmahmann — APPROVED** [review]
LGTM on the build side, although idk much about the port stuff.

**Pull request merged**
