### PR TITLE
bump to go-ipfs v0.5.0-rc2

### PR DESCRIPTION
**Pull request by MichaelMure**

### CODE REVIEW

**Comment by hsanjuan** [comment]
Tests are unhappy

**Comment by MichaelMure** [comment]
I think circle-ci should be bumped to go 1.13 or more.

**Comment by ianopolous** [comment]
It's complaining about go-ipfs using a different version of golang.org/x/net/html/atom

**Comment by Stebalien** [comment]
Well, I have no idea what's wrong here.

**Comment by Stebalien** [comment]
Turns out the AWS SDK version we were using was forcing an update to golang.org/x/net. I'm going to look into moving the plugins into go-ipfs itself and building them alongside go-ipfs.

**Comment by ianopolous** [comment]
Thank you so much. That's fantastic!

**Pull request merged**
