### PR TITLE
Add credentialsEndpoint config

### PR DESCRIPTION
**Pull request by lionello**
#107 added the `CredentialsEndpoint` config setting, but this could only be set programmatically. This patch adds a new key `credentialsEndpoint` to the config parser.

### CODE REVIEW

**Comment by lionello** [comment]
Looks like the CI has been broken for a while:
```
Error: error loading plugins: loading plugin /home/circleci/.ipfs/plugins/go-ds-s3.so: plugin.Open("/home/circleci/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package golang.org/x/sys/cpu
```

**Review by Stebalien — APPROVED** [review]
LGTM! Could you rebase on master? That should fix CI.

**Comment by lionello** [comment]
@Stebalien Done!

**Comment by Stebalien** [comment]
Thanks!

**Pull request merged**
