### PR TITLE
add support for prefix query filters

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
Unfortunately, I can't test this.

**Comment by Kubuxu** [comment]
I can't test it either.

**Comment by Stebalien** [comment]
Maybe... Mocking out AWS is probably more trouble than it's worth (unless amazon provides mocks).

**Comment by Stebalien** [comment]
No longer applies.

**Comment by postables** [comment]
I've been testing this out with minio (https://www.minio.io/) and it doesn't appear to be working. Queries will work so long as you don't restart the node, but after you restart the node it can no longer find the data you've pinned/upload.

**Comment by Stebalien** [comment]
Let's discuss that in https://github.com/ipfs/go-ds-s3/issues/10.

**Pull request closed without merging**
