### PR TITLE
Upgrade go-ipfs to 0.10.0

### PR DESCRIPTION
**Pull request by galargh**
When inspecting https://github.com/ipfs/go-ds-s3/pull/196 I noticed the CI runs fail on Go 1.7.

Here's the exact error:
```
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/runner/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132
FAIL	github.com/ipfs/go-ds-s3/plugin	0.026s
```
which points to https://github.com/marten-seemann/qtls-go1-15/blob/v0.1.1/unsafe.go#L20.

I've been able to reproduce the error by running `go test -v ./...` with Go 1.7 on PATH. Subsequently, I've been able to make it go away by upgrading `go-ipfs` here to either `0.9.1` or `0.10.0` (two separate commits in this PR). 

I have also run `LOCAL_S3=true go test -v ./...` using Go 1.6 with `go-ipfs` upgraded to `0.10.0`.

I'm still learning the space so I'd be curious to find out if an upgrade is the correct course of action here and/or if there's anything more we should take into account when performing the dependency upgrade.

### CODE REVIEW

**Comment by aschmahmann** [comment]
@galargh updating go-ipfs here seems reasonable. quic-go needs to do some unsafe shenanigans to interoperate with the underlying TLS library from Go. Sometimes the Go team breaks the underlying structures used for the TLS library which means that quic-go basically needs a separate binding per version of Go. It's policy is to support the latest two versions which is currently 1.16 and 1.17 and therefore not 1.15.

@marten-seemann is there a reasonable way to make the error any clearer here for future changes, or is this mostly the cost of doing business with build flags and unsafe Go bindings?

**Comment by galargh** [comment]
> note that this PR is failing since it runs 1.15 and 1.16 and bumping go-ipfs bumped the version of quic-go to one that no longer supports 1.15.

I see! That makes sense! Thank you for the explanation :)

Let me change the PR target to https://github.com/ipfs/go-ds-s3/pull/196 because that's where we change the Go versions being tested to 1.16 and 1.17.

**Comment by marten-seemann** [comment]
> @marten-seemann is there a reasonable way to make the error any clearer here for future changes, or is this mostly the cost of doing business with build flags and unsafe Go bindings?

Already done: https://github.com/lucas-clemente/quic-go/blob/master/internal/qtls/go118.go.

**Comment by marten-seemann** [comment]
There's a GitHub Actions workflow here that's not managed by Unified CI: https://github.com/ipfs/go-ds-s3/blob/master/.github/workflows/go-test-integration.yml. Not sure what the purpose is, as it's just running `go test`, so this _should_ be covered by the `go-test` workflow (with an additional setup setup for `docker-compose up`).

**Comment by galargh** [comment]
It also sets `LOCAL_S3` env var. Let me port that to our common CI setup in another PR.

**Comment by guseggert** [comment]
In [this PR](https://github.com/ipfs/go-ds-s3/pull/210) I have bumped this module to go-ipfs v0.11.0

**Pull request closed without merging**
